FROM python:3.11-slim
WORKDIR /app
RUN pip install "uv==0.11.7"
COPY uv.lock pyproject.toml ./
COPY libs/ libs/
COPY services/api/ services/api/
COPY services/worker/ services/worker/
RUN uv sync --no-dev
EXPOSE 8000
CMD ["uv", "run", "--package", "api", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
